/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

import javax.swing.JTextField;

/**
 *
 * @author sourav
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        jRadioButton1.setEnabled(true);
    }
    
    double number, answer;
    int calc;
    
    public void engine(){
        switch(calc){
            case 1: //Add
                answer=number+ Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(answer));
                break;
            case 2: //Substract
                answer=number- Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(answer));
                break;
            case 3: //Multiplication
                answer=number * Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(answer));
                break;
            case 4: //Division
                answer=number / Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(answer));
                break;
            case 5:
                answer=Math.sqrt(Double.parseDouble(jTextField1.getText()));
                jTextField1.setText(Double.toString(answer));
                break;
            case 6:
                answer=Math.pow(Double.parseDouble(jTextField1.getText()), 2);
                jTextField1.setText(Double.toString(answer));
                break;
            case 7:
                answer= Math.pow(number, Integer.parseInt(jTextField1.getText()));
                jTextField1.setText(Double.toString(answer));
                break;
        }
    }
    
    public void powerON(){
        jTextField1.setEnabled(true);
        BackspaceButton.setEnabled(true);
        One_Number_Button.setEnabled(true);
        DeleteAllButton.setEnabled(true);
        Two_Number_Button.setEnabled(true);
        SubtractionButton.setEnabled(true);
        Three_Number_Button.setEnabled(true);
        Six_Number_Button.setEnabled(true);
        Five_Number_Button.setEnabled(true);
        Four_Number_Button.setEnabled(true);
        EqualButton.setEnabled(true);
        Zero_Number_Button.setEnabled(true);
        Dot_Or_Point_Button.setEnabled(true);
        Seven_Number_Button.setEnabled(true);
        Eight_Number_Button.setEnabled(true);
        Nine_Number_Button.setEnabled(true);
        AdditionButton.setEnabled(true);
        MultificationButton.setEnabled(true);
        DivisionButton.setEnabled(true);
        
    }
    public void powerOFF(){
        jTextField1.setEnabled(false);
        BackspaceButton.setEnabled(false);
        One_Number_Button.setEnabled(false);
        DeleteAllButton.setEnabled(false);
        Two_Number_Button.setEnabled(false);
        SubtractionButton.setEnabled(false);
        Three_Number_Button.setEnabled(false);
        Six_Number_Button.setEnabled(false);
        Five_Number_Button.setEnabled(false);
        Four_Number_Button.setEnabled(false);
        EqualButton.setEnabled(false);
        Zero_Number_Button.setEnabled(false);
        Dot_Or_Point_Button.setEnabled(false);
        Seven_Number_Button.setEnabled(false);
        Eight_Number_Button.setEnabled(false);
        Nine_Number_Button.setEnabled(false);
        AdditionButton.setEnabled(false);
        MultificationButton.setEnabled(false);
        DivisionButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        BackspaceButton = new javax.swing.JButton();
        One_Number_Button = new javax.swing.JButton();
        DeleteAllButton = new javax.swing.JButton();
        Two_Number_Button = new javax.swing.JButton();
        SubtractionButton = new javax.swing.JButton();
        Three_Number_Button = new javax.swing.JButton();
        Six_Number_Button = new javax.swing.JButton();
        Five_Number_Button = new javax.swing.JButton();
        Four_Number_Button = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        Zero_Number_Button = new javax.swing.JButton();
        Dot_Or_Point_Button = new javax.swing.JButton();
        Seven_Number_Button = new javax.swing.JButton();
        Eight_Number_Button = new javax.swing.JButton();
        Nine_Number_Button = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();
        MultificationButton = new javax.swing.JButton();
        DivisionButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SquareButton = new javax.swing.JButton();
        log_button = new javax.swing.JButton();
        Square_Root_Button = new javax.swing.JButton();
        PowerButton = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        sin_button = new javax.swing.JButton();
        ln_button = new javax.swing.JButton();
        tan_button = new javax.swing.JButton();
        cos_button = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 102, 51));
        setLocation(new java.awt.Point(500, 200));
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setBackground(new java.awt.Color(16, 15, 52));
        jTextField1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jRadioButton1.setText("On");
        jRadioButton1.setToolTipText("Turns off Calculator");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.setToolTipText("Turns off calculator");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        BackspaceButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackspaceButton.setText("← ");
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        One_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        One_Number_Button.setText("1");
        One_Number_Button.setToolTipText("");
        One_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                One_Number_ButtonActionPerformed(evt);
            }
        });

        DeleteAllButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteAllButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        DeleteAllButton.setText("C");
        DeleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllButtonActionPerformed(evt);
            }
        });

        Two_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Two_Number_Button.setText("2");
        Two_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Two_Number_ButtonActionPerformed(evt);
            }
        });

        SubtractionButton.setBackground(new java.awt.Color(255, 153, 0));
        SubtractionButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        SubtractionButton.setText("-");
        SubtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionButtonActionPerformed(evt);
            }
        });

        Three_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Three_Number_Button.setText("3");
        Three_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Three_Number_ButtonActionPerformed(evt);
            }
        });

        Six_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Six_Number_Button.setText("6");
        Six_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Six_Number_ButtonActionPerformed(evt);
            }
        });

        Five_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Five_Number_Button.setText("5");
        Five_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Five_Number_ButtonActionPerformed(evt);
            }
        });

        Four_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Four_Number_Button.setText("4");
        Four_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Four_Number_ButtonActionPerformed(evt);
            }
        });

        EqualButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        EqualButton.setText("=");
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualButtonActionPerformed(evt);
            }
        });

        Zero_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Zero_Number_Button.setText("0");
        Zero_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zero_Number_ButtonActionPerformed(evt);
            }
        });

        Dot_Or_Point_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Dot_Or_Point_Button.setText(".");
        Dot_Or_Point_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dot_Or_Point_ButtonActionPerformed(evt);
            }
        });

        Seven_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Seven_Number_Button.setText("7");
        Seven_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seven_Number_ButtonActionPerformed(evt);
            }
        });

        Eight_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Eight_Number_Button.setText("8");
        Eight_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eight_Number_ButtonActionPerformed(evt);
            }
        });

        Nine_Number_Button.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        Nine_Number_Button.setText("9");
        Nine_Number_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nine_Number_ButtonActionPerformed(evt);
            }
        });

        AdditionButton.setBackground(new java.awt.Color(255, 153, 0));
        AdditionButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });

        MultificationButton.setBackground(new java.awt.Color(255, 153, 0));
        MultificationButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        MultificationButton.setText("×");
        MultificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultificationButtonActionPerformed(evt);
            }
        });

        DivisionButton.setBackground(new java.awt.Color(255, 153, 0));
        DivisionButton.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        DivisionButton.setText("÷");
        DivisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(236, 106, 85));

        SquareButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SquareButton.setText("x²");
        SquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareButtonActionPerformed(evt);
            }
        });

        log_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        log_button.setText("log");

        Square_Root_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Square_Root_Button.setText("√");
        Square_Root_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Square_Root_ButtonActionPerformed(evt);
            }
        });

        PowerButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        PowerButton.setText("^");
        PowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButtonActionPerformed(evt);
            }
        });

        jButton23.setText("!");

        sin_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sin_button.setText("sin");

        ln_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ln_button.setText("ln ");
        ln_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_buttonActionPerformed(evt);
            }
        });

        tan_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tan_button.setText("tan");

        cos_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cos_button.setText("cos");
        cos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(PowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(Square_Root_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SquareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Dot_Or_Point_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Zero_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Four_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Five_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Six_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Seven_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Eight_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Nine_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jRadioButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(One_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BackspaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Two_Number_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(DeleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Three_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SubtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MultificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(log_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ln_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SquareButton)
                        .addComponent(Square_Root_Button)
                        .addComponent(PowerButton)
                        .addComponent(jButton23)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln_button)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(One_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Two_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Three_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log_button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Four_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Five_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SubtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Six_Number_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Seven_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Eight_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nine_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dot_Or_Point_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Zero_Number_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tan_button)
                        .addGap(42, 42, 42)
                        .addComponent(cos_button)
                        .addGap(29, 29, 29)
                        .addComponent(sin_button)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        powerON();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        powerOFF(); //Calling powerOFF method
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void Two_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Two_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_Two_Number_ButtonActionPerformed

    private void SubtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionButtonActionPerformed
        number = Double.parseDouble(jTextField1.getText());
        calc=2;
        jTextField1.setText("");
        jLabel2.setText(number + " -");
    }//GEN-LAST:event_SubtractionButtonActionPerformed

    private void Three_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Three_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_Three_Number_ButtonActionPerformed

    private void Six_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Six_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_Six_Number_ButtonActionPerformed

    private void Five_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Five_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_Five_Number_ButtonActionPerformed

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualButtonActionPerformed
        engine();
        jLabel2.setText("");
    }//GEN-LAST:event_EqualButtonActionPerformed

    private void Zero_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zero_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_Zero_Number_ButtonActionPerformed

    private void Eight_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eight_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_Eight_Number_ButtonActionPerformed

    private void Nine_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nine_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_Nine_Number_ButtonActionPerformed

    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
        number = Double.parseDouble(jTextField1.getText());
        calc=1;
        jTextField1.setText("");
        jLabel2.setText(number + " +");
    }//GEN-LAST:event_AdditionButtonActionPerformed

    private void MultificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultificationButtonActionPerformed
        number = Double.parseDouble(jTextField1.getText());
        calc=3;
        jTextField1.setText("");
        jLabel2.setText(number + " *");
    }//GEN-LAST:event_MultificationButtonActionPerformed

    private void DivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButtonActionPerformed
        number = Double.parseDouble(jTextField1.getText());
        calc=4;
        jTextField1.setText("");
        jLabel2.setText(number + " /");
    }//GEN-LAST:event_DivisionButtonActionPerformed

    private void One_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_One_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_One_Number_ButtonActionPerformed

    private void Dot_Or_Point_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dot_Or_Point_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_Dot_Or_Point_ButtonActionPerformed

    private void Four_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Four_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_Four_Number_ButtonActionPerformed

    private void Seven_Number_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seven_Number_ButtonActionPerformed
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_Seven_Number_ButtonActionPerformed

    private void DeleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllButtonActionPerformed
        jTextField1.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_DeleteAllButtonActionPerformed

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonActionPerformed
        int length = jTextField1.getText().length();
        int number = jTextField1.getText().length()-1;
        String store;
        
        if (length>0){
            StringBuilder dlt = new StringBuilder(jTextField1.getText());
            dlt.deleteCharAt(number);
            store=dlt.toString();
            jTextField1.setText(store);
        }
    }//GEN-LAST:event_BackspaceButtonActionPerformed

    private void cos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cos_buttonActionPerformed

    private void Square_Root_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Square_Root_ButtonActionPerformed
        jLabel2.setText("SqureRoot("+jTextField1.getText()+")");
        calc=5;
        engine();
    }//GEN-LAST:event_Square_Root_ButtonActionPerformed

    private void SquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareButtonActionPerformed
        jLabel2.setText("Squreing("+jTextField1.getText()+")");
        calc=6;
        engine();
    }//GEN-LAST:event_SquareButtonActionPerformed

    private void PowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButtonActionPerformed
        jLabel2.setText(jTextField1.getText()+"^");
        calc=7;
        number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        engine();
    }//GEN-LAST:event_PowerButtonActionPerformed

    private void ln_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ln_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton BackspaceButton;
    private javax.swing.JButton DeleteAllButton;
    private javax.swing.JButton DivisionButton;
    private javax.swing.JButton Dot_Or_Point_Button;
    private javax.swing.JButton Eight_Number_Button;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton Five_Number_Button;
    private javax.swing.JButton Four_Number_Button;
    private javax.swing.JButton MultificationButton;
    private javax.swing.JButton Nine_Number_Button;
    private javax.swing.JButton One_Number_Button;
    private javax.swing.JButton PowerButton;
    private javax.swing.JButton Seven_Number_Button;
    private javax.swing.JButton Six_Number_Button;
    private javax.swing.JButton SquareButton;
    private javax.swing.JButton Square_Root_Button;
    private javax.swing.JButton SubtractionButton;
    private javax.swing.JButton Three_Number_Button;
    private javax.swing.JButton Two_Number_Button;
    private javax.swing.JButton Zero_Number_Button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cos_button;
    private javax.swing.JButton jButton23;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ln_button;
    private javax.swing.JButton log_button;
    private javax.swing.JButton sin_button;
    private javax.swing.JButton tan_button;
    // End of variables declaration//GEN-END:variables
}
